services:
  # Backend Service
  - type: web
    name: be-todo-02250377
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: todo-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: todo-db
          property: port
      - key: PORT
        value: "5000"
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: web
    name: fe-todo-02250377
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://be-todo-02250377.onrender.com

databases:
  - name: todo-db
    plan: free
    region: singapore